baseURL = "https://architchoudhary.xyz/"

theme = "notrack"
newContentEditor = "vim"
mainSections = ["blog"]
# disqusShortname = "example"
paginate = 4
title = "Archit Choudhary"

[params]
    author = "Archit Choudhary"
    siteHeading = "Archit Choudhary" # defaults to author
    favicon = "favicon.png" # Adds a small icon next to the page title in a tab
#    showBlogLatest = true
#    mainSections = ["blog"]
    showTaxonomyLinks = false
#    nBlogLatest = 4 # number of blog post on the home page
    footer = "© 2023 Archit Choudhary."

    [params.social]
        email = "thearchitc@gmail.com"
        github = "choudhary-archit"

[permalinks]
    blog = "/blog/:year/:month/:slug"

# I have to *manually* allow Hugo to access Vim.
[security]
    enableInlineShortcodes = false
        [security.exec]
            allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^vim$']
            osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

        [security.funcs]
            getenv = ['^HUGO_']

        [security.http]
            methods = ['(?i)GET|POST']
            urls = ['.*']
